import type { CharDef, MoveArt, MoveDef, MoveId } from './types'

function move(id: MoveId, name: string, art: MoveArt, rest: Omit<MoveDef, 'id' | 'name' | 'art'>): MoveDef {
  return { id, name, art, ...rest }
}


/**
 * VEX - the triangle. Light, quick, awkward to land a kill with until high
 * percent, but she gets in and out fast and has the best recovery.
 */
const VEX: CharDef = {
  id: 'vex',
  name: 'Vex',
  title: 'The Triangle',
  blurb: 'Three points, no patience. Fast frames and a huge recovery, but she folds the moment you catch her.',
  sides: 3,
  rotation: -Math.PI / 2,
  radius: 13,
  colors: {
    body: '#4fd6ff',
    shade: '#1f8ec9',
    outline: '#0a2536',
    accent: '#ffe066',
    eye: '#0a2536',
  },
  weight: 0.86,
  walk: 2.05,
  groundAccel: 0.55,
  friction: 0.72,
  airAccel: 0.32,
  airMax: 1.85,
  gravity: 0.42,
  fallMax: 6.6,
  fastFallMax: 10.2,
  jump: -8.0,
  doubleJump: -7.2,
  jumps: 2,
  hurt: { w: 20, h: 20 },
  face: { dy: 4, spread: 3.4, size: 2 },
  stats: { power: 2, speed: 5, weight: 2 },
  moves: {
    jab: move('jab', 'Point Blank', 'jab', {
      startup: 3,
      active: 3,
      recovery: 7,
      damage: 3,
      baseKb: 11,
      kbScale: 0.3,
      angle: 42,
      hit: { x: 12, y: 13, w: 12, h: 10 },
    }),
    side: move('side', 'Edge Dash', 'swing', {
      startup: 7,
      active: 4,
      recovery: 13,
      damage: 9,
      baseKb: 20,
      kbScale: 0.62,
      angle: 33,
      hit: { x: 15, y: 12, w: 16, h: 14 },
      selfVel: { x: 2.6 },
      shake: 2,
    }),
    up: move('up', 'Apex Spin', 'spin', {
      startup: 5,
      active: 5,
      recovery: 11,
      damage: 7,
      baseKb: 19,
      kbScale: 0.6,
      angle: 84,
      hit: { x: 0, y: 27, w: 22, h: 15 },
      symmetric: true,
      shake: 2,
    }),
    down: move('down', 'Wedge Drop', 'stomp', {
      startup: 8,
      active: 5,
      recovery: 15,
      damage: 8,
      baseKb: 14,
      kbScale: 0.42,
      angle: -72,
      hit: { x: 0, y: 3, w: 20, h: 11 },
      symmetric: true,
      selfVel: { y: 3.4 },
      shake: 3,
    }),
    special: move('special', 'Ricochet', 'burst', {
      startup: 4,
      active: 9,
      recovery: 14,
      damage: 6,
      baseKb: 17,
      kbScale: 0.42,
      angle: 76,
      hit: { x: 0, y: 24, w: 18, h: 22 },
      symmetric: true,
      selfVel: { x: 1.6, y: -8.4 },
      killsMomentum: true,
      helplessAfter: true,
      shake: 2,
    }),
  },
}

/**
 * GRUM - the hexagon. Slow, heavy, and every button he presses is a threat.
 * Struggles to get back on stage, so knock him off and keep him there.
 */
const GRUM: CharDef = {
  id: 'grum',
  name: 'Grum',
  title: 'The Hexagon',
  blurb: 'Six sides of bad news. Everything he throws kills, but he moves like a boulder and dies off the edge.',
  sides: 6,
  rotation: Math.PI / 6,
  radius: 15,
  colors: {
    body: '#ff8a3d',
    shade: '#c4531a',
    outline: '#361005',
    accent: '#ffe066',
    eye: '#361005',
  },
  weight: 1.32,
  walk: 1.35,
  groundAccel: 0.34,
  friction: 0.78,
  airAccel: 0.22,
  airMax: 1.25,
  gravity: 0.47,
  fallMax: 7.4,
  fastFallMax: 11.0,
  jump: -7.5,
  doubleJump: -6.6,
  jumps: 2,
  hurt: { w: 26, h: 28 },
  face: { dy: -1, spread: 4.2, size: 2.4 },
  stats: { power: 5, speed: 2, weight: 5 },
  moves: {
    jab: move('jab', 'Knuckle', 'jab', {
      startup: 5,
      active: 4,
      recovery: 10,
      damage: 5,
      baseKb: 13,
      kbScale: 0.36,
      angle: 36,
      hit: { x: 14, y: 15, w: 14, h: 12 },
    }),
    side: move('side', 'Haymaker', 'swing', {
      startup: 13,
      active: 4,
      recovery: 21,
      damage: 16,
      baseKb: 30,
      kbScale: 0.8,
      angle: 39,
      hit: { x: 17, y: 15, w: 19, h: 17 },
      selfVel: { x: 1.6 },
      shake: 6,
    }),
    up: move('up', 'Girder', 'rise', {
      startup: 8,
      active: 6,
      recovery: 17,
      damage: 12,
      baseKb: 26,
      kbScale: 0.72,
      angle: 88,
      hit: { x: 3, y: 32, w: 20, h: 19 },
      selfVel: { y: -3.2 },
      shake: 4,
    }),
    down: move('down', 'Quake', 'quake', {
      startup: 10,
      active: 6,
      recovery: 19,
      damage: 11,
      baseKb: 22,
      kbScale: 0.52,
      angle: 58,
      hit: { x: 0, y: 7, w: 34, h: 13 },
      symmetric: true,
      killsMomentum: true,
      shake: 5,
    }),
    special: move('special', 'Bunker Buster', 'burst', {
      startup: 7,
      active: 10,
      recovery: 18,
      damage: 9,
      baseKb: 19,
      kbScale: 0.4,
      angle: 80,
      hit: { x: 0, y: 28, w: 22, h: 24 },
      symmetric: true,
      selfVel: { x: 0.9, y: -7.2 },
      killsMomentum: true,
      helplessAfter: true,
      shake: 3,
    }),
  },
}

export const ROSTER: CharDef[] = [VEX, GRUM]

export function charById(id: string): CharDef {
  return ROSTER.find((c) => c.id === id) ?? ROSTER[0]
}
